### ISSUE TITLE
Deploy failing because unspecified platform and region

### ISSUE THREAD

**Issue by davichoar** [bentoml/google-cloud-run-deploy#2]
When trying to use the deploy script in Ubuntu 18.04 and Google Cloud SDK 339.0.0, the deploy.py script expects a region and a platform in the `gcloud run deploy` command. I believe this would happen when the run/platform and the run/region properties are not set beforehand.

**Comment by davichoar** [comment]
#3

**Comment by jjmachan** [comment]
fixed in #3 Thanks again for bringing this up and putting the fix in @davichoar 🙌🏽

**Comment by davichoar** [comment]
> fixed in #3 Thanks again for bringing this up and putting the fix in @davichoar 🙌🏽

No problem! Thanks to you for the deployment repos of bentoml 💯
