### ISSUE TITLE
Adding argparse and rich too google cloud run deploy

### ISSUE THREAD

**Issue by jjmachan** [bentoml/google-cloud-run-deploy#5]
Argparse is a python library to parse the CLI arguments better and provide help messages and improve the CLI experience. You can check out the [docs](https://docs.python.org/3/howto/argparse.html) to know more. It would be great to add argparse to the scripts here. You can use the [EC2 deployment tool](https://github.com/bentoml/aws-ec2-deploy/blob/f1c03c9c43183b2b3cf5b7cb61a006f609ce578e/deploy.py#L143) as reference. 

We are also adding a library called rich to the deployment tools to improve the UI of tool with color and spinners and it would be great to add it here too

![image](https://github.com/bentoml/aws-ec2-deploy/blob/main/demo.gif?raw=true)

this is a demo of how it works for EC2 and the idea is to add a similar experience here as well. You can refer to the EC2 deployment tools for reference too.

**Comment by johntharian** [comment]
[Deploy #7](https://github.com/bentoml/google-cloud-run-deploy/pull/7)
